name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn run build
    - name: Create .npmrc
      run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm }}
    - name: update git account
      run: git config user.name youhan26
    - name: update git 
      run: git config user.email youhan26@gmail.com
    - name: update version
      run: npm version patch
    - name: publish
      run: npm publish --no-git-tag-version
